import { Component, type ReactNode, useEffect, useState } from 'react';
import { Link, NavLink, Route, Routes, useLocation, useParams } from 'react-router-dom';
import { ArrowUpRight, ArrowRight, Github, Mail, Menu, X, Download, MapPin, Cpu, AudioLines, Layers, ScanEye, ChartNoAxesCombined, Check } from 'lucide-react';
import { SplineScene } from '@/components/ui/splite';
import { Spotlight } from '@/components/ui/spotlight';
import { Card } from '@/components/ui/card';
import Timeline from '@/components/ui/timeline';

const github = 'https://github.com/NaReddyJashwanthReddy';
const email = 'jashwanthreddysungjin@gmail.com';
const projects = [
  {id:'agents',title:'AI that takes action.',name:'Multi-Agent & Voice Assistants',category:'Agentic AI',icon:AudioLines,tags:['LangGraph','RAG','STT / TTS'],description:'From a Telegram message to a completed workflow. Multi-service agents and conversational voice assistants.',details:'Built a Telegram assistant that detects intent and routes email, calendar, news, and travel requests. RAG supports knowledge queries, while Google APIs execute actions. A separate travel-sales voice assistant connects speech recognition, an LLM, travel retrieval, and text-to-speech.',visual:'agents'},
  {id:'llm',title:'Language, adapted.',name:'LLM Fine-Tuning & Domain Adaptation',category:'Generative AI',icon:Cpu,tags:['Qwen3','PyTorch','Hugging Face'],description:'Adapting language models for natural conversation and domain-specific knowledge.',details:'Prepared role-structured, multi-turn chat examples and fine-tuned a conversational LLM for concise replies, evaluating on unseen prompts. Continued pretraining of Qwen3 used a curated corpus of approximately 20 medical books across specialties to explore domain terminology for a health-information assistant.',visual:'llm'},
  {id:'vision',title:'Beyond what meets the eye.',name:'Multimodal Image Analysis',category:'Computer Vision',icon:ScanEye,tags:['CLIP','YOLO','OpenCV'],description:'Turning pixels and language into structured, explainable image assessments.',details:'Built an image-and-text pipeline that returns structured JSON with a quality score, visual drawbacks, and explanations. CLIP experiments support semantic ranking, while YOLO and OpenCV pipelines enable object-level image analysis.',visual:'vision'},
  {id:'generative',title:'From noise to possibility.',name:'Generative Models from Scratch',category:'Generative AI',icon:Layers,tags:['GANs','Diffusion','U-Net'],description:'Building the mechanics of image generation, one training loop at a time.',details:'Implemented GAN generator and discriminator architectures on CIFAR, adversarial losses, alternating optimization, and sample generation. Built a diffusion model with a forward noise schedule, timestep conditioning, U-Net noise prediction, and iterative reverse denoising.',visual:'generative'},
  {id:'analytics',title:'Data with a direction.',name:'Predictive ML & Analytics',category:'Machine Learning',icon:ChartNoAxesCombined,tags:['XGBoost','Optuna','FastAPI'],description:'Connecting predictive models with decisions. Loan approval achieved 0.97070 public leaderboard ROC-AUC.',details:'Created a churn intelligence workflow using SQL, exploratory analysis, Random Forest, stratified cross-validation, FastAPI, Power BI, and A/B-testing design. Built a loan-approval classifier with XGBoost and Random Forest, Optuna tuning, and five-fold cross-validation; public leaderboard ROC-AUC was 0.97070.',visual:'analytics'},
];

class SceneBoundary extends Component<{children:ReactNode},{failed:boolean}> {
  state={failed:false};
  static getDerivedStateFromError(){return {failed:true}}
  render(){return this.state.failed ? <div className="scene-fallback"><Cpu size={90}/><p>The 3D scene is unavailable.</p></div> : this.props.children}
}
function Scene(){const [enabled,setEnabled]=useState(false);const [reduce,setReduce]=useState(false);useEffect(()=>{const query=matchMedia('(prefers-reduced-motion: reduce)');setReduce(query.matches);const update=()=>setReduce(query.matches);query.addEventListener('change',update);return()=>query.removeEventListener('change',update)},[]);return <div className="scene"><Spotlight size={220} className="from-blue-400/15 via-blue-300/10 to-transparent"/><div className="scene-glow"/>{!reduce||enabled ? <SceneBoundary><SplineScene scene="https://prod.spline.design/kZDDjO5HuC9GJUM2/scene.splinecode" className="spline-canvas"/></SceneBoundary>:<button className="scene-fallback" onClick={()=>setEnabled(true)}><Cpu size={90}/>Load interactive 3D</button>}<span className="scene-caption"><span className="live-dot"/> INTERACTIVE INTELLIGENCE <span>01 / 03</span></span></div>}
function ProjectCard({project,index}:{project:typeof projects[number],index:number}){const Icon=project.icon;return <Link to={`/projects/${project.id}`} className="project-card"><div className={`project-art ${project.visual}`}><div className="art-grid"/><Icon className="art-icon" size={64} strokeWidth={1}/><span className="art-caption">{project.category.toUpperCase()} / 0{index+1}</span><ArrowUpRight className="art-arrow" size={22}/><div className="art-orbit"/></div><div className="project-copy"><div className="eyebrow">{project.category}</div><h3>{project.title}</h3><p>{project.description}</p><div className="tags">{project.tags.map(t=><span key={t}>{t}</span>)}</div></div></Link>}
function Home(){return <><section className="hero shell"><div className="hero-copy"><div className="eyebrow"><span className="live-dot"/> AI ENGINEER · MELBOURNE, AU</div><h1>Building intelligence.<br/><span>Making it matter.</span></h1><p className="intro">I’m Jashwanth. I turn ideas into AI systems that see, understand, and act — from computer vision to generative AI.</p><div className="actions"><Link className="button primary" to="/projects">Explore my work <ArrowUpRight size={18}/></Link><a className="button secondary" href="/resume.pdf" download>Download resume <Download size={16}/></a></div><div className="hero-note"><span className="mini-avatar">JR</span><div>Engineer. Experimenter. Lifelong learner.<small>Currently pursuing an M.AI at Monash University.</small></div></div></div><Scene/></section><section className="metrics shell"><div><strong>&gt;99<span>%</span></strong><p>Vision detection accuracy</p><small>Production systems at Fotos</small></div><div><strong>60<span>%</span></strong><p>Less manual editing effort</p><small>Neural color style transfer</small></div><div><strong>0.9707</strong><p>Loan approval ROC-AUC</p><small>Kaggle public leaderboard</small></div><div><strong>M.AI</strong><p>Monash University</p><small>2026–Present</small></div></section><section className="section shell"><div className="section-head"><div><div className="eyebrow">01 / SELECTED WORK</div><h2>Ideas, engineered.</h2></div><Link className="text-link" to="/projects">All projects <ArrowUpRight size={18}/></Link></div><div className="project-grid">{[projects[0],projects[2],projects[1]].map((p,i)=><ProjectCard key={p.id} project={p} index={i}/>)}</div></section><section className="about-strip shell"><div className="eyebrow">02 / THE APPROACH</div><h2>Curiosity is the starting point.<br/><span>Production is the destination.</span></h2><div><p>I work across the full AI pipeline: preparing data, training models, building inference APIs, and monitoring systems in the cloud.</p><Link className="text-link" to="/journey">My experience & education <ArrowRight size={18}/></Link></div></section><section className="section shell"><div className="eyebrow">03 / TOOLKIT</div><div className="toolkit">{['Python','PyTorch','TensorFlow','LangGraph','Hugging Face','OpenCV','FastAPI','GCP','Docker','SQL'].map(t=><span key={t}>{t}</span>)}</div></section><ContactBanner/></>}
function Projects(){const [filter,setFilter]=useState('All');const categories=['All','Agentic AI','Generative AI','Computer Vision','Machine Learning'];return <main className="shell page"><div className="eyebrow">THE PROJECT ARCHIVE</div><h1>Experiments.<br/><span>Built into systems.</span></h1><p className="intro">A selection of work across agents, language, vision, and predictive intelligence.</p><div className="filters" aria-label="Filter projects">{categories.map(c=><button aria-pressed={filter===c} className={filter===c?'active':''} onClick={()=>setFilter(c)} key={c}>{c}</button>)}</div><div className="project-grid archive">{projects.filter(p=>filter==='All'||p.category===filter).map(p=><ProjectCard key={p.id} project={p} index={projects.indexOf(p)}/>)}</div></main>}
function ProjectDetail(){const {id}=useParams();const p=projects.find(p=>p.id===id);if(!p)return <NotFound/>;const Icon=p.icon;return <main className="shell page detail"><Link className="text-link" to="/projects">← Back to projects</Link><div className="eyebrow">{p.category}</div><h1>{p.name}</h1><p className="intro">{p.description}</p><div className={`detail-art project-art ${p.visual}`}><div className="art-grid"/><Icon size={100} strokeWidth={1}/><div className="art-orbit"/></div><div className="detail-body"><h2>What I built</h2><p>{p.details}</p><h3>Tools & technologies</h3><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><a className="button secondary" href={github} target="_blank" rel="noreferrer">Explore my GitHub profile <Github size={18}/></a><p className="fine-print">Project descriptions are based on my resume. Repository links will be added when confirmed.</p></div></main>}
const milestones=[['2020–2024','BVRIT · B.Tech','Electrical & Electronic Engineering · CGPA 8.05/10. AI & ML minor · CGPA 8.90/10.'],['2023','Innovation & AI competitions','ATVC Innovation Runner-Up · My Anatomy AI-thon Finalist.'],['Jan–Feb 2024','Navodita InfoTech · AI Intern','NLP chatbot and transformer-based French–English translation.'],['Feb 2025–Jan 2026','Fotos · AI Engineer','Production computer vision, photo culling, generative style transfer, GCP deployment, and inference APIs.'],['2026–Present','Monash University · Master of AI','Current WAM 79.0 · GPA 3.5.']];
function Journey(){return <main><div className="shell page journey-intro"><div className="eyebrow">EDUCATION & EXPERIENCE</div><h1>Always learning.<br/><span>Always building.</span></h1><p className="intro">From electrical engineering to production AI, and now a Master of Artificial Intelligence.</p><span className="scroll-hint">Scroll to explore the journey ↓</span></div><div className="desktop-timeline"><Timeline title="My Journey" periodLabel="2020 — Present" textColor="#eef3ff" mutedTextColor="#a2afc6" activeColor="#76a7ff" backgroundColor="#080c14" imageUrl="/journey.svg" imageAlt="Abstract atom illustration: from circuits to intelligence" duration={1.4}/></div><div className="shell simple-timeline">{milestones.map(([date,title,copy])=><article key={title}><div className="eyebrow">{date}</div><h2>{title}</h2><p>{copy}</p></article>)}</div><section className="shell section"><div className="eyebrow">CERTIFICATION</div><Card className="certificate"><h3>Advanced Data Science & AI</h3><p>Intellipaat (IIT-Madras)</p></Card></section><ContactBanner/></main>}
function ContactBanner(){return <section className="contact-banner shell"><div><div className="eyebrow">LET’S CONNECT</div><h2>Have something<br/><span>worth building?</span></h2></div><Link className="button primary" to="/contact">Let’s talk <ArrowUpRight size={20}/></Link></section>}
function Contact(){const [copied,setCopied]=useState(false);const [status,setStatus]=useState('');async function copy(){try{await navigator.clipboard.writeText(email);setCopied(true);setStatus('Email copied.');setTimeout(()=>setCopied(false),2500)}catch{setStatus('Select and copy the email address below.')}}return <main className="shell page contact-page"><div className="eyebrow">START A CONVERSATION</div><h1>Good things start<br/><span>with a hello.</span></h1><p className="intro">Let’s connect about AI engineering, collaborations, or an interesting problem to solve.</p><div className="contact-layout"><a href={`mailto:${email}`} className="email-card"><Mail size={30}/><small>EMAIL ME</small><h2>{email}</h2><span className="text-link">Open your email app <ArrowUpRight size={18}/></span></a><div className="contact-links"><a href={github} target="_blank" rel="noreferrer"><Github/>GitHub <ArrowUpRight/></a><a href="https://www.kaggle.com/jashwanthreddy0264" target="_blank" rel="noreferrer"><ChartNoAxesCombined/>Kaggle <ArrowUpRight/></a><p><MapPin/>Melbourne, Victoria, Australia</p><button className="button secondary" onClick={copy}>{copied?<Check size={16}/>:<Mail size={16}/>} {copied?'Copied email':'Copy email address'}</button><p role="status">{status}</p></div></div><a className="text-link" href="/resume.pdf" download>Download my resume <Download size={18}/></a></main>}
function NotFound(){return <main className="shell page"><div className="eyebrow">404</div><h1>Page not found.</h1><Link className="button primary" to="/">Back home <ArrowRight/></Link></main>}
export default function App(){const [open,setOpen]=useState(false);const location=useLocation();useEffect(()=>{window.scrollTo(0,0);setOpen(false);const title=location.pathname.startsWith('/projects')?'Projects':location.pathname==='/journey'?'Journey':location.pathname==='/contact'?'Contact':'AI Engineer';document.title=`${title} | Jashwanth Reddy`},[location.pathname]);return <><a className="skip-link" href="#content">Skip to content</a><header className="header shell"><Link className="brand" to="/" aria-label="Jashwanth Reddy home">jashwanth<span>.</span><small>AI ENGINEER</small></Link><button className="menu-toggle" aria-label={open?'Close navigation':'Open navigation'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'open':''}>{[['/','Home'],['/projects','Projects'],['/journey','Journey'],['/contact','Contact']].map(([path,label])=><NavLink key={path} to={path} end={path==='/'}>{label}</NavLink>)}</nav><a className="header-contact" href={`mailto:${email}`}>Let’s connect <ArrowUpRight size={16}/></a></header><div id="content"><Routes><Route path="/" element={<Home/>}/><Route path="/projects" element={<Projects/>}/><Route path="/projects/:id" element={<ProjectDetail/>}/><Route path="/journey" element={<Journey/>}/><Route path="/contact" element={<Contact/>}/><Route path="*" element={<NotFound/>}/></Routes></div><footer className="shell footer"><Link className="brand" to="/">jashwanth<span>.</span></Link><p>© {new Date().getFullYear()} Jashwanth Reddy</p><a href={github} target="_blank" rel="noreferrer" aria-label="GitHub"><Github size={19}/></a><a href={`mailto:${email}`} aria-label="Email"><Mail size={19}/></a><span>BUILT WITH CURIOSITY ↗</span></footer></>}

